### PR TITLE
My New Project - CGLondrina

### PR DESCRIPTION
**Pull request by HudsonNicoletti**

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Thank you

**Comment by andresgutierrez** [comment]
Screenshot is broken: https://builtwith.phalconphp.com/

**Comment by HudsonNicoletti** [comment]
Fixed :smile:

**Comment by andresgutierrez** [comment]
This is the URL: https://static.phalconphp.com/builtwith/projects/CG-Londrina/thumb.png

**Pull request merged**
