### PR TITLE
Adding new site: https://outsmart.io

### PR DESCRIPTION
**Pull request by tkroll**
Adding new site: https://outsmart.io

### CODE REVIEW

**Comment by sergeyklay** [comment]
Cc: @niden

**Comment by tkroll** [comment]
How often do you update the site?

**Comment by niden** [comment]
@tkroll Thanks for the reminder. Sorry it took this long

**Comment by tkroll** [comment]
Thanks for the quick response. I had to do another pull request. I didn't use the correct image. Thanks.

**Pull request merged**
