### PR TITLE
added The Dealio

### PR DESCRIPTION
**Pull request by zhegwood**
I launched the V1 of my site today!  More features and things to come, but this is it for now.

### CODE REVIEW

**Comment by andresgutierrez** [comment]
Thanks

**Comment by andresgutierrez** [comment]
Screenshot is broken: https://builtwith.phalconphp.com/

**Comment by zhegwood** [comment]
Looking at the code...  It's searching for the image at this url:

https://static.phalconphp.com/builtwith/projects/the dealio/thumb.png

when it should be this url:

https://static.phalconphp.com/builtwith/projects/the-dealio/thumb.png (with
the dash)

I don't think this is an issue w/ the changes I made to the repo... Seems
like a path issue in the code.

Thanks,
-Zach

**Comment by zhegwood** [comment]
Wait, maybe I need to change the "permalink": "the-dealio" in the json?  Please let me know.

**Pull request merged**
